version: '3.5'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: notverysecure
# might need to choose a specific data directory via env variable
    ports:
      - 5432:5432
    volumes:
      - ./local_data:/data
      - .:/container_root_dir

  web:
    build: ""
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

