version: '3.1'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: notverysecure
# might need to choose a specific data directory via env variable
    ports:
      - 5432:5432

      

# not sure I need this, as I'm not interacting with psql through the web browser
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
